### ISSUE TITLE
Data Review Tool UI: specify and make any changes

### ISSUE THREAD

**Issue by kd-ods** [openownership/cove-bods#104]
In the first place: look at https://datareview.openownership.org/ and https://github.com/openownership/cove-bods/tree/master to check whether any UI revisions are needed.

**Comment by kd-ods** [comment]
### Change 1

In the 'Validation errors' table there is a 'First 3 Examples' column. This lists the values of the field where there is an error. Currently, in the case that the following was in BODS data:

```
{
...
    "share": {
        "exact": "99"
    {
...
}
```
Users would get the message in the validator : 

> `exact` should be a number. Check that the value is not null, and doesn’t contain any characters other than 0-9 and dot (<code>.</code>). Number values should not be in quotes.

But then in the examples column they would see:

> 99

It would generally help usability if string values were shown between quote marks in the 'First 3 Examples' column.

**Comment by kathryn-ods** [comment]
Idk if this is UI but a thought. 

If there are no errors we have a message e.g. "There were no validation errors!" "There were no additional fields!"

Can we swap exclamation mark for a full stop here? It's conveying enthusiasm I think but the tone seems a bit out of place to me.

**Comment by kathryn-ods** [comment]
I find the links in the header of the tool a bit confusing. 

Currently:
- Beneficial Ownership Data Standard (BODS) and BODS Documentation link to the schema 
- Data Review Tool links to the Data Review Tool

I would expect the main header link to be for the front page of the data review tool - this keeps catching me out when I want to go to the homepage to load a new data set. 

Maybe it should be 

Beneficial Ownership Data Standard (BODS) Data Review Tool as one phrase all linking to the homepage of the review tool (remove the link between these). And then the BODS Documentation link still goes to the docs. 

![Image](https://github.com/user-attachments/assets/18b0f12b-89cc-4bf7-9372-69404ba0caf3)
