### ISSUE TITLE
statementID that is an object causes a 500 error

### ISSUE THREAD

**Issue by Bjwebb** [openownership/cove-bods#67]
Minimal example:

```
[{"statementID": {}}]
```

**Comment by mpostelnicu** [comment]
i noticed the same problem while using the tool on some badly formatted sample data, we need a more verbose error, something point out to `statementId` being invalid type

**Comment by odscjames** [comment]
![Uploading id_must_be_string.png…]()

**Comment by odscjames** [comment]
![id_must_be_string](https://user-images.githubusercontent.com/37832009/134187019-6a8c424e-4b0d-44a8-81af-128b0f376eb1.png)

**Comment by odscjames** [comment]
Deployed
