### ISSUE TITLE
publicationDetails and isComponent fields are not considered part of BODS

### ISSUE THREAD

**Issue by mpostelnicu** [openownership/cove-bods#68]
Hi, 

I noticed that `publicationDetails` and `isComponent` fields are ignored from validation and are considered "additional fields" meaning not present in the JSON schema. Both fields are required under BODS 0.2.0.

**Comment by kd-ods** [comment]
Thanks, @mpostelnicu - I can't replicate this using a couple of small datasets I have. I'll DM you to work out what's going on.

**Comment by mpostelnicu** [comment]
I found out what the problem is. According to the schema, `bodsVersion` is supposed to be a String, not a number. However if a number is used by mistake, the validator does not issue a schema invalid error (probably because the chosen schema is actually based on this field), but it simply ignores the field and defaults to version 0.1 , which does not have a `publicationDetails` field, it then treats the `publicationDetails` field as a new field that is not covered by the schema, and reports it accordingly. 

So in this code, `bodsVersion` is ignored:

```
"publicationDetails": {
          "publicationDate": "2021-01-01",
            "bodsVersion": 0.2,
            "publisher": {
                "name": "Some Publisher"
      }
```
I wonder if COVE should not default to 0.2 instead of 0.1 since 0.1 seems to be lacking some basic building blocks for publication, like the `publicationDetails`. Is 0.1 in active use ?

**Comment by kd-ods** [comment]
> I wonder if COVE should not default to 0.2 instead of 0.1 since 0.1 seems to be lacking some basic building blocks for publication, like the publicationDetails. Is 0.1 in active use ?

No, 0.1 isn't in active use. Rather than defaulting to validate against 0.2, I wonder whether users could get a clear message in the UI:

"No valid bodsVersion property has been found in these statements. The statements are being validated against BODS v0.1."

Or something to that effect.

**Comment by kd-ods** [comment]
Closing this issue as a symptom of this bug: https://github.com/openownership/cove-bods/issues/56.
