### ISSUE TITLE
Wording of error message needs changing

### ISSUE THREAD

**Issue by siwhitehouse** [openownership/cove-bods#7]
I attempted to upload an invalid file and received the error message:

"BODS JSON should have an list as the top level, the JSON you supplied does not."

This should either read "a list" or it is missing something between 'an' and 'list'.

URL is http://cove.cove-dev-bods.default.opendataservices.uk0.bigv.io/data/2ce19931-ab71-423a-ba20-493e726a5a2d

**Comment by Bjwebb** [comment]
Fixed in https://dev.datareview.openownership.org/
