### ISSUE TITLE
Add Sample Mode

### ISSUE THREAD

**Issue by odscjames** [openownership/cove-bods#79]
Split out from #69

Motivation: Users who have large files won't be able to process them using the DRT. Instead they can follow some simple instructions to create a sample file locally of a smaller size and upload that instead. This won't be able to check everything, but it will be able to check a lot of things and hopefully that will still help users.

On the home page of the tool, every upload method will have a "sample data" or "full data" switch in the UI. This could be radio buttons or a select box. ("full data" by default)

In sample mode, certain tests are not run - there wouldn't be any tests that need a full file to check properly, and thus can't be checked in a sample file. Eg:

* Person or Entity statement not used by a ownership/control statement
* ownership/control statement refers to a person or entity that does not exist
* ordering checks

To do this work: 

The sample mode would be added as a flag to libcovebods. (off by default)

Then the tool would be updated with a switch in the UI that is passed to libcovebods.

An issue here is that currently the home page of the tool comes from libcoveweb, which is shared with other tools. It might be possible to add the functionality to the shared library, but behind a switch so that other tools don't get it. Or it might be possible to extend the library from the cove app itself.

**Comment by odscjames** [comment]
I've had a look again and I will estimate 3 days - I haven't totally worked out how to extend libcove in a clean way, so that might throw up some surprises.

**Comment by kd-ods** [comment]
Work on this is at the final stages.

@kd-ods to supply @odscjames with a doc outlining UI elements to guide people's use and understanding of Sample Mode.

**Comment by kd-ods** [comment]
@odscjames - how random is the sampling in Sample mode going to be? That is: if someone runs the same large dataset through COVE twice with sample mode on, will the subset of statements tested be different each time?

**Comment by odscjames** [comment]
It's not random at all - it takes the first statements it encounters.

**Comment by kd-ods** [comment]
Thanks @odscjames. I think that's fine, but we need to get that information to users of the Tool. I've updated the UI spec with suggested edits.

**Comment by StephenAbbott** [comment]
Closing this issue following completion of work listed in https://github.com/openownership/cove-bods/pull/97
